-- AlterEnum
ALTER TYPE "Status" ADD VALUE 'LNC';
ALTER TYPE "Status" ADD VALUE 'B_LNC';
ALTER TYPE "Status" ADD VALUE 'LC';
ALTER TYPE "Status" ADD VALUE 'B_LC';
ALTER TYPE "Status" ADD VALUE 'COMMUNICATION';
ALTER TYPE "Status" ADD VALUE 'TRASH';
